before:
  hooks:
    - go mod download

release:
  prerelease: auto

builds:
- env:
    - CGO_ENABLED=0
  main: main.go
  goos:
    - linux
  goarch:
    - arm
  goarm:
    - 7

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - '^ci:'

archives:
  - name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

nfpms:
  - id: default
    file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    vendor: Sergei Kasatkin
    maintainer: Sergei Kasatkin
    homepage: https://github.com/kstkn/woody
    license: MIT License
    formats:
      - deb
    conflicts:
      - woody
    bindir: /usr/bin
